@echo off
ren "E:\TV SERIES\ARCHER\Season 7\S07-E01.mp4" "Archer_S07E01.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E02.mp4" "Archer_S07E02.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E03.mp4" "Archer_S07E03.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E04.mp4" "Archer_S07E04.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E05.mp4" "Archer_S07E05.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E06.mp4" "Archer_S07E06.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E07.mp4" "Archer_S07E07.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E08.mp4" "Archer_S07E08.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E09.mp4" "Archer_S07E09.mp4"
ren "E:\TV SERIES\ARCHER\Season 7\S07-E10.mp4" "Archer_S07E10.mp4"
ren "E:\TV SERIES\ARCHER\Season 8\[fmovies.to] Archer 8 - 01.mp4" "Archer_S08E01.mp4"
ren "E:\TV SERIES\ARCHER\Season 8\[fmovies.to] Archer 8 - 02.mp4" "Archer_S08E02.mp4"
ren "E:\TV SERIES\ARCHER\Season 8\[fmovies.to] Archer 8 - 03.mp4" "Archer_S08E03.mp4"
ren "E:\TV SERIES\ARCHER\Season 8\[fmovies.to] Archer 8 - 04.mp4" "Archer_S08E04.mp4"
ren "E:\TV SERIES\ARCHER\Season 8\[fmovies.to] Archer 8 - 05.mp4" "Archer_S08E05.mp4"
ren "E:\TV SERIES\ARCHER\Season 8\[fmovies.to] Archer 8 - 06.mp4" "Archer_S08E06.mp4"
ren "E:\TV SERIES\ARCHER\Season 8\[fmovies.to] Archer 8 - 07.mp4" "Archer_S08E07.mp4"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (02).avi" "BattlestarGalactica_S02E21_2.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (03).avi" "BattlestarGalactica_S02E21_3.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (04).avi" "BattlestarGalactica_S02E21_4.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (05).avi" "BattlestarGalactica_S02E21_5.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (06).avi" "BattlestarGalactica_S02E21_6.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (07).avi" "BattlestarGalactica_S02E21_7.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (08).avi" "BattlestarGalactica_S02E21_8.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (09).avi" "BattlestarGalactica_S02E21_9.avi"
ren "E:\TV SERIES\BATTLESTAR\S02E21 - The Resistance (10).avi" "BattlestarGalactica_S02E21_10.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (02).avi" "BattlestarGalactica_S04E10.5_2.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (03).avi" "BattlestarGalactica_S04E10.5_3.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (04).avi" "BattlestarGalactica_S04E10.5_4.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (05).avi" "BattlestarGalactica_S04E10.5_5.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (06).avi" "BattlestarGalactica_S04E10.5_6.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (07).avi" "BattlestarGalactica_S04E10.5_7.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (08).avi" "BattlestarGalactica_S04E10.5_8.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (09).avi" "BattlestarGalactica_S04E10.5_9.avi"
ren "E:\TV SERIES\BATTLESTAR\S04E10.5 - The Face of the Enemy (10).avi" "BattlestarGalactica_S04E10.5_10.avi"
ren "E:\TV SERIES\BETTER CALL SAUL\Season 3\[fmovies.to] Better Call Saul 3 - 01.mp4" "BetterCallSaul_S03E01.mp4"
ren "E:\TV SERIES\BETTER CALL SAUL\Season 3\[fmovies.to] Better Call Saul 3 - 02.mp4" "BetterCallSaul_S03E02.mp4"
ren "E:\TV SERIES\BETTER CALL SAUL\Season 3\[fmovies.to] Better Call Saul 3 - 03.mp4" "BetterCallSaul_S03E03.mp4"
ren "E:\TV SERIES\BETTER CALL SAUL\Season 3\[fmovies.to] Better Call Saul 3 - 04.mp4" "BetterCallSaul_S03E04.mp4"
ren "E:\TV SERIES\BETTER CALL SAUL\Season 3\[fmovies.to] Better Call Saul 3 - 05.mp4" "BetterCallSaul_S03E05.mp4"
ren "E:\TV SERIES\BETTER CALL SAUL\Season 3\[fmovies.to] Better Call Saul 3 - 06.mp4" "BetterCallSaul_S03E06.mp4"
ren "E:\TV SERIES\BETTER CALL SAUL\Season 3\[fmovies.to] Better Call Saul 3 - 07.mp4" "BetterCallSaul_S03E07.mp4"
ren "E:\TV SERIES\DOCOS\Future of Food (2009)\BBC - Future of Food (2009) - 1 - India.avi" "DOCO_FutureOfFood_S01E01.avi"
ren "E:\TV SERIES\DOCOS\Future of Food (2009)\BBC - Future of Food (2009) - 2 - Senegal.avi" "DOCO_FutureOfFood_S01E02.avi"
ren "E:\TV SERIES\DOCOS\Future of Food (2009)\BBC - Future of Food (2009) - 3 - Cuba.avi" "DOCO_FutureOfFood_S01E03.avi"
ren "E:\TV SERIES\DOCOS\HAWKINGS DOCO\Discovery.Ch.Stephen.Hawkings.Grand.Design.1of3.The.Key.to.the.Cosmos.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_Hawkings_S01E01.avi"
ren "E:\TV SERIES\DOCOS\HAWKINGS DOCO\Discovery.Ch.Stephen.Hawkings.Grand.Design.2of3.The.Meaning.of.Life.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_Hawkings_S01E02.avi"
ren "E:\TV SERIES\DOCOS\HAWKINGS DOCO\Discovery.Ch.Stephen.Hawkings.Grand.Design.3of3.Did.God.Create.the.Universe.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_Hawkings_S01E03.avi"
ren "E:\TV SERIES\DOCOS\Journey of Life (2005)\BBC - Journey of Life (2005) - 01 - Seas of Life.avi" "DOCO_JourneyOfLife_S01E01.avi"
ren "E:\TV SERIES\DOCOS\Journey of Life (2005)\BBC - Journey of Life (2005) - 02 - Land Grab.avi" "DOCO_JourneyOfLife_S01E02.avi"
ren "E:\TV SERIES\DOCOS\Journey of Life (2005)\BBC - Journey of Life (2005) - 03 - Airborne.avi" "DOCO_JourneyOfLife_S01E03.avi"
ren "E:\TV SERIES\DOCOS\Journey of Life (2005)\BBC - Journey of Life (2005) - 04 - Living Together.avi" "DOCO_JourneyOfLife_S01E04.avi"
ren "E:\TV SERIES\DOCOS\Journey of Life (2005)\BBC - Journey of Life (2005) - 05 - Human Life.avi" "DOCO_JourneyOfLife_S01E05.avi"
ren "E:\TV SERIES\DOCOS\Life in Cold Blood (2008)\BBC - Life in Cold Blood (2008) - 1 - The Cold-Blood (2008)ed Truth.avi" "DOCO_LifeInColdBlood_S01E01.avi"
ren "E:\TV SERIES\DOCOS\Life in Cold Blood (2008)\BBC - Life in Cold Blood (2008) - 2 - Land Invaders.avi" "DOCO_LifeInColdBlood_S01E02.avi"
ren "E:\TV SERIES\DOCOS\Life in Cold Blood (2008)\BBC - Life in Cold Blood (2008) - 3 - Dragons Of The Dry.avi" "DOCO_LifeInColdBlood_S01E03.avi"
ren "E:\TV SERIES\DOCOS\Life in Cold Blood (2008)\BBC - Life in Cold Blood (2008) - 4 - Sophisticated Serpents.avi" "DOCO_LifeInColdBlood_S01E04.avi"
ren "E:\TV SERIES\DOCOS\Life in Cold Blood (2008)\BBC - Life in Cold Blood (2008) - 5 - Armoured Giants.avi" "DOCO_LifeInColdBlood_S01E05.avi"
ren "E:\TV SERIES\DOCOS\Life in the Freezer (1993)\BBC - Life in the Freezer (1993) - 01 - The Bountiful Sea.avi" "DOCO_LifeInTheFreezer_S01E01.avi"
ren "E:\TV SERIES\DOCOS\Life in the Freezer (1993)\BBC - Life in the Freezer (1993) - 02 - The Ice Retreats.avi" "DOCO_LifeInTheFreezer_S01E02.avi"
ren "E:\TV SERIES\DOCOS\Life in the Freezer (1993)\BBC - Life in the Freezer (1993) - 03 - The Race To Breed.avi" "DOCO_LifeInTheFreezer_S01E03.avi"
ren "E:\TV SERIES\DOCOS\Life in the Freezer (1993)\BBC - Life in the Freezer (1993) - 04 - The Door Closes.avi" "DOCO_LifeInTheFreezer_S01E04.avi"
ren "E:\TV SERIES\DOCOS\Life in the Freezer (1993)\BBC - Life in the Freezer (1993) - 05 - The Big Freeze.avi" "DOCO_LifeInTheFreezer_S01E05.avi"
ren "E:\TV SERIES\DOCOS\Life in the Freezer (1993)\BBC - Life in the Freezer (1993) - 06 - Footsteps in the Snow.avi" "DOCO_LifeInTheFreezer_S01E06.avi"
ren "E:\TV SERIES\DOCOS\Life in the Undergrowth (2005)\BBC - Life in the Undergrowth (2005) - 01 - Invasion of the Land.avi" "DOCO_LifeInTheUndergrowth_S01E01.avi"
ren "E:\TV SERIES\DOCOS\Life in the Undergrowth (2005)\BBC - Life in the Undergrowth (2005) - 02 - Taking to the Air.avi" "DOCO_LifeInTheUndergrowth_S01E02.avi"
ren "E:\TV SERIES\DOCOS\Life in the Undergrowth (2005)\BBC - Life in the Undergrowth (2005) - 03 - The Silk Spinners.avi" "DOCO_LifeInTheUndergrowth_S01E03.avi"
ren "E:\TV SERIES\DOCOS\Life in the Undergrowth (2005)\BBC - Life in the Undergrowth (2005) - 04 - Intimate Relations.avi" "DOCO_LifeInTheUndergrowth_S01E04.avi"
ren "E:\TV SERIES\DOCOS\Life in the Undergrowth (2005)\BBC - Life in the Undergrowth (2005) - 05 - Supersocities.avi" "DOCO_LifeInTheUndergrowth_S01E05.avi"
ren "E:\TV SERIES\DOCOS\Life in the Undergrowth (2005)\BBC - Life in the Undergrowth (2005) - Extra - Fly on the Wall.avi" "DOCO_LifeInTheUndergrowth_S01E06.avi"
ren "E:\TV SERIES\DOCOS\Life in the Undergrowth (2005)\BBC - Life in the Undergrowth (2005) - Extra - Making of.avi" "DOCO_LifeInTheUndergrowth_S01E07.avi"
ren "E:\TV SERIES\DOCOS\MATHS\BBC.The.Story.of.Maths.1of4.The.Language.of.the.Universe.PDTV.x264.AAC.MVGroup.org.wmv" "DOCO_StoryofMath_S01E01.wmv"
ren "E:\TV SERIES\DOCOS\MATHS\BBC.The.Story.of.Maths.2of4.The.Genius.of.the.East.PDTV.x264.AAC.MVGroup.org.wmv" "DOCO_StoryofMath_S01E02.wmv"
ren "E:\TV SERIES\DOCOS\MATHS\BBC.The.Story.of.Maths.3of4.The.Frontiers.of.Space.PDTV.x264.AAC.MVGroup.org.wmv" "DOCO_StoryofMath_S01E03.wmv"
ren "E:\TV SERIES\DOCOS\MATHS\BBC.The.Story.of.Maths.4of4.To.Infinity.and.Beyond.PDTV.x264.AAC.MVGroup.org.wmv" "DOCO_StoryofMath_S01E04.wmv"
ren "E:\TV SERIES\DOCOS\MONEY\Ch4.The.Ascent.of.Money.1of6.Dreams.of.Avarice.XviD.AC3.MVGroup.org.avi" "DOCO_AcentofMoney_S01E01.avi"
ren "E:\TV SERIES\DOCOS\MONEY\Ch4.The.Ascent.of.Money.2of6.Human.Bondage.XviD.AC3.MVGroup.org.avi" "DOCO_AcentofMoney_S01E02.avi"
ren "E:\TV SERIES\DOCOS\MONEY\Ch4.The.Ascent.of.Money.3of6.Blowing.Bubbles.XviD.AC3.MVGroup.org.avi" "DOCO_AcentofMoney_S01E03.avi"
ren "E:\TV SERIES\DOCOS\MONEY\Ch4.The.Ascent.of.Money.4of6.Risky.Business.XviD.AC3.MVGroup.org.avi" "DOCO_AcentofMoney_S01E04.avi"
ren "E:\TV SERIES\DOCOS\MONEY\Ch4.The.Ascent.of.Money.5of6.Safe.as.Houses.XviD.AC3.MVGroup.org.avi" "DOCO_AcentofMoney_S01E05.avi"
ren "E:\TV SERIES\DOCOS\MONEY\Ch4.The.Ascent.of.Money.6of6.Chimerica.XviD.AC3.MVGroup.org.avi" "DOCO_AcentofMoney_S01E06.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.1of8.Oceans.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E01.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.2of8.Deserts.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E02.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.3of8.Arctic.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E03.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.4of8.Jungles.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E04.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.5of8.Mountains.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E05.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.6of8.Grasslands.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E06.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.7of8.Rivers.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E07.avi"
ren "E:\TV SERIES\DOCOS\PLANET\BBC.Human.Planet.8of8.Cities.XviD.AC3.MVGroup.org.avi" "DOCO_HumanPlanet_S01E08.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.1of8.Volcanoes.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E01.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.2of8.Megastorms.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E02.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.3of8.Planets.from.Hell.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E03.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.4of8.Megaflares.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E04.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.5of8.Extreme.Orbits.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E05.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.6of8.Comets.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E06.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.7of8.Asteroids.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E07.avi"
ren "E:\TV SERIES\DOCOS\Universe Doc\Discovery.Ch.How.the.Universe.Works.Series.2.8of8.Birth.of.the.Earth.PDTV.XviD.AC3.MVGroup.org.avi" "DOCO_HowTheUniverseWorks_S01E08.avi"
ren "E:\TV SERIES\EXPANSE\Season 2\The.Expanse.S02E05.HDTV.x264-SVA[eztv].mkv" "TheExpanse_S02E05.mkv"
ren "E:\TV SERIES\GAME OF THRONES\GAME OF THRONES S06\Game.of.Thrones.S06E03.RERIP.720p.HDTV.x264-AVS[eztv].mkv" "GameOfThrones_S06E03.mkv"
ren "E:\TV SERIES\HUNG\Hung - Season 1\Hung 01x05 - Do it, Monkey!.avi" "Hung_S01E05.avi"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\00 - Dig Deeper.MP4" "Insanity_Dig Deeper.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\01 - Fit Test.MP4" "Insanity_Fit Test.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\02 - Plyometric Cardio Circuit.MP4" "Insanity_Plyometric Cardio Circuit.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\03 - Cardio Power & Resistance.MP4" "Insanity_Cardio Power & Resistance.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\04 - Cardio Recovery.MP4" "Insanity_Cardio Recovery.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\05 - Pure Cardio.MP4" "Insanity_Pure Cardio.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\06 - Cardio Abs.MP4" "Insanity_Cardio Abs.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\07 - Core Cardio & Balance.MP4" "Insanity_Core Cardio & Balance.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\08 - Max Interval Circuit.MP4" "Insanity_Max Interval Circuit.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\09 - Max Interval Plyo.MP4" "Insanity_Max Interval Plyo.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\10 - Max Cardio Conditioning.MP4" "Insanity_Max Cardio Conditioning.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\11 - Max Recovery.MP4" "Insanity_Max Recovery.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\12 - Insane Abs.MP4" "Insanity_Insane Abs.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\13 - Max Interval Sports Training.MP4" "Insanity_Max Interval Sports Training.MP4"
ren "E:\TV SERIES\KETTLEBELLS\Insanity\14 - Upper Body Weight Training.MP4" "Insanity_Upper Body Weight Training.MP4"
ren "E:\TV SERIES\ROBOT CHICKEN SW\Robot Chicken - Star Wars Episode I.avi" "RobotChick_StarWars_S01E01.avi"
ren "E:\TV SERIES\ROBOT CHICKEN SW\Robot Chicken - Star Wars Episode II.avi" "RobotChick_StarWars_S01E02.avi"
ren "E:\TV SERIES\ROBOT CHICKEN SW\Robot.Chicken.Star.Wars.Episode.III.HDTV.XviD-2HD.avi" "RobotChick_StarWars_S01E03.avi"
ren "E:\TV SERIES\The Thick Of It\Season 1\The Thick of It 1 - 01.mp4" "TheThickofIt_S01E01.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 1\The Thick of It 1 - 02.mp4" "TheThickofIt_S01E02.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 1\The Thick of It 1 - 03.mp4" "TheThickofIt_S01E03.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 2\The Thick of It 2 - 1.mp4" "TheThickofIt_S02E01.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 2\The Thick of It 2 - 2.mp4" "TheThickofIt_S02E02.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 2\The Thick of It 2 - 3.mp4" "TheThickofIt_S02E03.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 01.mp4" "TheThickofIt_S03E01.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 02.mp4" "TheThickofIt_S03E02.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 03.mp4" "TheThickofIt_S03E03.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 04.mp4" "TheThickofIt_S03E04.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 05.mp4" "TheThickofIt_S03E05.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 06.mp4" "TheThickofIt_S03E06.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 07.mp4" "TheThickofIt_S03E07.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 08.mp4" "TheThickofIt_S03E08.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 09.mp4" "TheThickofIt_S03E09.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 3\The Thick of It 3 - 10.mp4" "TheThickofIt_S03E10.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 4\The Thick of It 4 - 1.mp4" "TheThickofIt_S04E01.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 4\The Thick of It 4 - 2.mp4" "TheThickofIt_S04E02.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 4\The Thick of It 4 - 3.mp4" "TheThickofIt_S04E03.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 4\The Thick of It 4 - 4.mp4" "TheThickofIt_S04E04.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 4\The Thick of It 4 - 5.mp4" "TheThickofIt_S04E05.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 4\The Thick of It 4 - 6.mp4" "TheThickofIt_S04E06.mp4"
ren "E:\TV SERIES\The Thick Of It\Season 4\The Thick of It 4 - 7.mp4" "TheThickofIt_S04E07.mp4"
ren "E:\TV SERIES\The Thick Of It\Specials\The Thick of It Specials - 1.mp4" "TheThickofIt_S05E01.mp4"
ren "E:\TV SERIES\The Thick Of It\Specials\The Thick of It Specials - 2.mp4" "TheThickofIt_S05E02.mp4"
ren "E:\TV SERIES\The Thick Of It\Specials\The Thick of It Specials - 3.mp4" "TheThickofIt_S05E03.mp4"
ren "E:\TV SERIES\White Gold, Season 1, All 6 Episodes\White Gold - 1x01 - Salesmen Are Like Vampires.mkv" "WhiteGold_S01E01.mkv"
ren "E:\TV SERIES\White Gold, Season 1, All 6 Episodes\White Gold - 1x02 - Sexy Rollercoaster.mkv" "WhiteGold_S01E02.mkv"
ren "E:\TV SERIES\White Gold, Season 1, All 6 Episodes\White Gold - 1x03 - Close Encounters.mkv" "WhiteGold_S01E03.mkv"
ren "E:\TV SERIES\White Gold, Season 1, All 6 Episodes\White Gold - 1x04 - The Widow Maker.mkv" "WhiteGold_S01E04.mkv"
ren "E:\TV SERIES\White Gold, Season 1, All 6 Episodes\White Gold - 1x05 - Smell the Weakness.mkv" "WhiteGold_S01E05.mkv"
ren "E:\TV SERIES\White Gold, Season 1, All 6 Episodes\White Gold - 1x06 - The Secret of Sales.mkv" "WhiteGold_S01E06.mkv"

pause